apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nhs-app
  name: nhs-app-2
spec:
  containers:
  - image: nginx
    name: nhs-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
