apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kratos
    service: webserver
  name: kratos
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
