apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/nader/dk8s.git
    targetRevision: HEAD
    path: observability/monitoring
    helm:
      releaseName: monitoring
      valueFiles:
        - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
