apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
spec:
  project: default
  source:
    repoURL: https://github.com/nader/dk8s.git
    targetRevision: HEAD
    path: argocd/observability/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
